### PR TITLE
Fix load problem in IE (Promise is not defined)

### PR DESCRIPTION
**Pull request by chuckdumont**

### CODE REVIEW

**Comment by ddumontatibm** [comment]
lgtm, but where are you using es6 promises in the sample app?

**Comment by chuckdumont** [comment]
The bootstrap code generated by Webpack uses ES6 promises

**Comment by ddumontatibm** [comment]
:-/   So this means that any app using that will have this problem.   Don't you want a solution that the integrating app doesn't need to worry about?

The dojo-webpack-plugin should be able to assume that dojo is available, right?

**Comment by chuckdumont** [comment]
I don't really want to include it by default.  Not many people will care about supporting IE. I'll add a note in the readme about it

**Pull request merged**
